title: Practical Community Management
description: Launch and Grow Online Communities Like a Pro. All best practices of leading community managers that one needs to know.
theme: just-the-docs

url: https://course.practical-cm.com

logo: "/assets/images/practical_cm_logo.png"

favicon_ico: "/assets/images/practical_cm_favicon.ico"

ga_tracking: G-0XWR07SBQR

#plugins:
#  - jekyll-sitemap